blank_issues_enabled: true
contact_links:
  - name: Moonlight Support
    url: https://t.me/the_nightt_club
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://Yukki.tech/
    about: Documentation for getting started with bot.
